### PR TITLE
fix: oxygen sealer mechanics

### LINKED ISSUE #461: Oxygen tanks deplete and Invalid Oxygen Setup warning appears when in sealed area
### Version Information

c51c7bc

### Log or Crash Report

_No response_

### Reproduction steps

Go to an environment where there is no oxygen
Make a small shack and place an oxygen sealer with an infinite tank and infinite battery
Observe invalid setup warning
Put on oxygen setup with any tank (non infinite)
Hover over oxygen bar, press shift, observe the value dropping

### PR DESCRIPTION
**Pull request by davo899**
Resolves #461

### CODE REVIEW

**Comment by davo899** [comment]
Fixes #461

**Comment by Roelymole** [comment]
If you use closes or resolves instead of fixes, the issue will be linked properly so that merging the pull request closes the issue. The same applies if you write it in a commit message.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 1]
```diff
@@ -128,12 +119,10 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
     @Override
     protected @NotNull MachineStatus tick(@NotNull ServerLevel level, @NotNull BlockPos pos, @NotNull BlockState state, @NotNull ProfilerFiller profiler) {
         // Check if the machine has enough energy
-        SealerManager manager = ((GCLevelAccessor) level).getSealerManager();
         if (!this.energyStorage().canExtract(Galacticraft.CONFIG.oxygenSealerEnergyConsumptionRate())) {
             //recalculate area to avoid issues with fake oxygen
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: This comment seems outdated and should probably be removed.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 2]
```diff
@@ -128,12 +119,10 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
...
             if (this.hasEnergy) {
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: This if statement is probably unnecessary now.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 3]
```diff
@@ -144,7 +133,6 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
             //recalculate area to avoid issues with fake oxygen
             if (this.hasOxygen) {
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: The same thing applies here, as above.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 4]
```diff
@@ -154,27 +142,23 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
             //recalculate area to avoid issues with fake oxygen
             if (!this.blocked) {
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: Here too.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 5]
```diff
@@ -154,27 +142,23 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
...
             return GCMachineStatuses.BLOCKED;
         }
         this.blocked = false;
 
-        // Update sealing status periodically
+        // Timer for display on UI
         if (this.sealCheckTimer-- <= 0) {
             this.sealCheckTimer = SEAL_CHECK_TIME;
-            manager.recalculateSealingStatus(pos, level);
         }
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: Can you ensure this `sealCheckTimer` is synced with the `SealerManager`'s `sealCheckTimer`?

If not it might just be better to use the `SealerManager`'s in the UI directly.

File: src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java [hunk 6]
```diff
@@ -31,10 +31,10 @@
 @Mixin(Level.class)
 public class LevelMixin implements GCLevelAccessor {
     @Unique
-    private final SealerManager sealerManager = new SealerManager();
+    private final SealerManager sealerManager = new SealerManager((Level)(Object)this);
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java]: It might be slightly neater to separate the casts with spaces, like so: `(Level) (Object) this`

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java (hunk 5 above)
Comment (davo899) [reply src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: The issue is client vs server side, sealer manager shouldn't really exist on the client side at all but im not entirely sure how to rework that properly. Any thoughts?

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java (hunk 2 above)
Comment (davo899) [reply src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: Im a bit confused about this, aren't these if statements controlling the status in the sealer's UI?

Comment (davo899) [reply src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: Nevermind, I get what you mean now lol

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java (hunk 5 above)
Comment (Roelymole) [reply src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java]: Good point. Perhaps the simplest thing to do would be to recheck whenever the `level.getGameTime() % SEAL_CHECK_TIME == 0`.

**Comment by Roelymole** [comment]
Will you have a chance to look at my other comments at some point soon?

**Comment by davo899** [comment]
I will tomorrow, sorry

File: src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java [hunk 7]
```diff
@@ -31,10 +31,10 @@
 @Mixin(Level.class)
 public class LevelMixin implements GCLevelAccessor {
     @Unique
-    private final SealerManager sealerManager = new SealerManager();
+    private final SealerManager sealerManager = new SealerManager((Level) (Object) this);
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java:34]: Also, for mixins you should use the `@Final` decorator from `org.spongepowered.asm.mixin.Final` rather than the final keyword.

File: src/main/java/dev/galacticraft/mod/machine/SealerManager.java [hunk 8]
```diff
@@ -23,147 +23,128 @@
...
-        for (Map.Entry<BlockPos, OxygenSealerBlockEntity> entry : this.sealers.entrySet()) {
-            if (entry.getKey().distSqr(pos) <= OxygenSealerBlockEntity.SEALER_RANGE * OxygenSealerBlockEntity.SEALER_RANGE) {
-                return entry.getKey();
-            }
+    private static final double MAX_SEALER_VOLUME = 1024;
+
+    public void tick() {
+        // Update sealing status periodically
+        if (this.sealCheckTimer-- <= 0) {
+            this.sealCheckTimer = SEAL_CHECK_TIME;
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/machine/SealerManager.java:68]: This is still not necessarily in sync, but if you were to check whether `level.getGameTime() % SEAL_CHECK_TIME == 0` here it should work.

Setting `SEAL_CHECK_TIME` to a larger value for testing should make it more obvious if they are in sync or not.

Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/machine/SealerManager.java:68]: This is still not necessarily in sync, but if you were to check whether `level.getGameTime() % SEAL_CHECK_TIME == 0` here it should work.

Setting `SEAL_CHECK_TIME` to a larger value for testing should make it more obvious if they are in sync or not.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 9]
```diff
@@ -222,14 +189,15 @@ public boolean hasEnergy() {
...
     }
 
     public boolean isBlocked() {
         return this.blocked;
     }
 
     public int getSealTickTime() {
-        return this.sealCheckTimer;
+        if (level == null) return 0;
+        return (int) (level.getGameTime() % SEAL_CHECK_TIME);
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java:201]: Thinking about it, we want to count down to the next check, so it should be `SEAL_CHECK_TIME - (int) (level.getGameTime() % SEAL_CHECK_TIME)`.

File: src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java [hunk 10]
```diff
@@ -128,53 +117,32 @@ protected void tickConstant(@NotNull ServerLevel level, @NotNull BlockPos pos, @
...
 
         // Check if the oxygen tank is empty
         if (this.fluidStorage().slot(OXYGEN_TANK).isEmpty()) {
-            //recalculate area to avoid issues with fake oxygen
-            if (this.hasOxygen) {
-                this.hasOxygen = false;
-                manager.recalculateSealingStatus(pos, level);
-            }
+            this.hasOxygen = false;
             return GCMachineStatuses.NOT_ENOUGH_OXYGEN;
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/content/block/entity/machine/OxygenSealerBlockEntity.java:129]: This is not currently taking into account how much oxygen there is, just that there is some, meaning that the sealer could run on less oxygen than it technically requires.

At the moment the `consumeOxygen` method extracts the amount returned by `Galacticraft.CONFIG.oxygenSealerOxygenConsumptionRate()`, so at the very least you should check if you can extract that much (similarly to the energy above).

I imagine in the future we will want to scale the amount of oxygen required by how many blocks are being sealed which will probably require a slightly different approach, but if you have time maybe you could try doing this now. This amount would have to be shared between sealers if there are multiple sealers in the same space, which might be slightly fiddly.

File: src/main/java/dev/galacticraft/mod/machine/SealerManager.java [hunk 11]
```diff
@@ -23,147 +23,128 @@
...
+            if (!sealer.hasEnergy()) continue;
+            if (!sealer.hasOxygen()) continue;
+            if (sealer.isBlocked()) continue;
+
+            // Flood fill to find all blocks this sealer is trying to seal
+            SpaceToSeal spaceToSeal = new SpaceToSeal(sealer);
+            while (!spaceToSeal.floodFillQueue.isEmpty()) {
+                BlockPos pos = spaceToSeal.floodFillQueue.pollFirst();
+                if (spaceToSeal.blocksToSeal.contains(pos)) continue;
+                if (!level.getBlockState(pos).isAir()) continue;
```
Comment (Roelymole) [inline src/main/java/dev/galacticraft/mod/machine/SealerManager.java:100]: The only blocks for which the `isAir()` method returns true are `Blocks.AIR`, `Blocks.VOID_AIR` and `Blocks.CAVE_AIR`, which means that a room could be sealed with something like a torch as part of the wall.

File: src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java (hunk 7 above)
Comment (marcus8448) [reply src/main/java/dev/galacticraft/mod/mixin/LevelMixin.java:34]: I don't think `@Final` applies here - its not a shadowed field.
