### PR TITLE
fix: remove unnecessary redirect, narrow down other one

### LINKED ISSUE #114: Conflict with mod (fabric-carpet)
When I have installed carpet mod and latest galacticraft (`Galacticraft-5.0.0-prealpha+build.ba3af9e6.jar`), the game is immediately crashes
crash report fragment:
`[19:39:45] [main/WARN]: @Redirect conflict. Skipping galacticraft.mixins.json:client.WorldRendererMixin->@Redirect::useThickFogGC(Lnet/minecraft/class_5294;II)Z with priority 1000, already redirected by carpet.mixins.json:WorldRenderer_fogOffMixin->@Redirect::isReallyThick(Lnet/minecraft/class_5294;II)Z with priority 69420`

full crash report: http://vpaste.net/xEY4B

### PR DESCRIPTION
**Pull request by marcus8448**
Fixes #114

### CODE REVIEW

File: src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java [hunk 1]
```diff
@@ -43,7 +44,7 @@ public Vec3d adjustFogColor(Vec3d color, float sunHeight) {
 
     @Override
     public boolean useThickFog(int camX, int camY) {
-        return false;
+        return MinecraftClient.getInstance().world.getBiome(MinecraftClient.getInstance().cameraEntity.getBlockPos()).getFogColor() == 1447446;
```
Comment (craftablescience) [inline src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java:47]: Is it possible to make this number 0x161616 for readability, or does that break it?

**Review by craftablescience — CHANGES_REQUESTED** [review]

File: src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java (hunk 1 above)
Comment (craftablescience) [reply src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java:47]: image
Looks like it should work out

**Review by craftablescience — APPROVED** [review]
